In [3]:
using(LinearAlgebra)

In [47]:
x = rand(1000)

1000-element Array{Float64,1}:
 0.34167595461708244
 0.683628843398912  
 0.4545742090874949 
 0.8001695390352854 
 0.8619912456806458 
 0.07321234232669038
 0.33344448377374336
 0.6034386040173743 
 0.3273871778546307 
 0.6500670011741281 
 0.08683912913615677
 0.8147481430653587 
 0.31126261787188003
 ⋮                  
 0.3388944257834203 
 0.2713265209514262 
 0.7403897371528019 
 0.16808423050047905
 0.8710767019544283 
 0.655042896822146  
 0.13669065005072123
 0.17770527446610807
 0.5921030653591897 
 0.9878435704849007 
 0.5166093978749962 
 0.7830135085538517 

In [46]:
A = rand(1000,1000)

1000×1000 Array{Float64,2}:
 0.670162  0.943741   0.266763   0.979694  …  0.657921   0.9779     0.573238 
 0.358135  0.83802    0.374641   0.647084     0.700115   0.0893339  0.325823 
 0.817683  0.87584    0.909412   0.101379     0.0154712  0.720432   0.386433 
 0.130805  0.480207   0.449907   0.47093      0.0537666  0.297504   0.446986 
 0.794165  0.779202   0.943711   0.179181     0.835419   0.244345   0.476269 
 0.505769  0.153213   0.978479   0.347331  …  0.427293   0.0633604  0.248922 
 0.148839  0.799749   0.0442035  0.282874     0.219799   0.874212   0.971889 
 0.546416  0.0957083  0.0626681  0.194144     0.234192   0.354089   0.978547 
 0.921119  0.897262   0.372501   0.175219     0.0416243  0.248312   0.455073 
 0.386722  0.691763   0.782551   0.802177     0.164345   0.911438   0.647271 
 0.109148  0.257711   0.310714   0.860757  …  0.542921   0.331552   0.929574 
 0.173882  0.944256   0.434721   0.551967     0.815321   0.854636   0.0149526
 0.437644  0.62554    0.499201   0.5

In [48]:
b=A*x

1000-element Array{Float64,1}:
 256.8267040567061 
 248.63338466556078
 243.92877426460248
 260.55702820416195
 254.9995173906949 
 253.30655887696398
 246.33742888409722
 249.02237603457405
 244.18925996485416
 247.41497894407627
 253.2262916346207 
 259.49083767352727
 252.55335834347383
   ⋮               
 249.67418433433343
 260.50829619280415
 260.01265486398364
 247.68660892215814
 257.2599842390103 
 255.13014983828833
 245.2883082286131 
 249.28906614388538
 259.1805036562258 
 248.0836270513686 
 249.3256523661232 
 250.890853070399  

In [49]:
inv(A)*b

1000-element Array{Float64,1}:
 0.341675954616516  
 0.6836288433985516 
 0.45457420908791235
 0.8001695390321117 
 0.8619912456802385 
 0.07321234232720819
 0.333444483774322  
 0.6034386040167448 
 0.3273871778552522 
 0.6500670011742251 
 0.08683912913597869
 0.8147481430655468 
 0.3112626178716482 
 ⋮                  
 0.3388944257831916 
 0.2713265209552702 
 0.7403897371524266 
 0.1680842305008241 
 0.8710767019545838 
 0.655042896822458  
 0.1366906500504328 
 0.17770527446638518
 0.5921030653590265 
 0.9878435704849817 
 0.5166093978747464 
 0.7830135085538608 

In [50]:
x=A\b

1000-element Array{Float64,1}:
 0.34167595461743816
 0.6836288433991587 
 0.45457420908769053
 0.8001695390352863 
 0.8619912456806027 
 0.07321234232642006
 0.3334444837738077 
 0.6034386040170064 
 0.32738717785469257
 0.6500670011739006 
 0.08683912913611287
 0.8147481430655495 
 0.3112626178716992 
 ⋮                  
 0.338894425783592  
 0.27132652095158155
 0.7403897371527867 
 0.1680842305004002 
 0.8710767019547034 
 0.6550428968222127 
 0.1366906500505986 
 0.17770527446606263
 0.5921030653589995 
 0.9878435704848634 
 0.5166093978752219 
 0.7830135085537911 

In [51]:
A = factorize(A)
A\b

1000-element Array{Float64,1}:
 0.34167595461743816
 0.6836288433991587 
 0.45457420908769053
 0.8001695390352863 
 0.8619912456806027 
 0.07321234232642006
 0.3334444837738077 
 0.6034386040170064 
 0.32738717785469257
 0.6500670011739006 
 0.08683912913611287
 0.8147481430655495 
 0.3112626178716992 
 ⋮                  
 0.338894425783592  
 0.27132652095158155
 0.7403897371527867 
 0.1680842305004002 
 0.8710767019547034 
 0.6550428968222127 
 0.1366906500505986 
 0.17770527446606263
 0.5921030653589995 
 0.9878435704848634 
 0.5166093978752219 
 0.7830135085537911 

In [53]:
x = rand(1000);
A = rand(1000,1000);
b=A*x;
@time inv(A)*b;
@time A\b;
@time (A = factorize(A); A\b);

  0.112509 seconds (11 allocations: 8.134 MiB)
  0.094201 seconds (9 allocations: 7.645 MiB)
  0.096777 seconds (9 allocations: 7.645 MiB, 1.26% gc time)


In [94]:
x = rand(1000);
A = rand(1000,1000);
b=A*x;
j = inv(A)*b;
k = A\b;
A = factorize(A);
l = A\b;
println(sqrt(dot(j,x)));
println(sqrt(dot(k,x)));
println(sqrt(dot(l,x)));

18.387414796658952
18.387414796658707
18.387414796658707


In [54]:
using CSV
input="times.csv"
mydata=CSV.read(input, delim=";")

190×4 DataFrames.DataFrame
│ Row │ size   │ time_better │ time_naive │ time_blas │
│     │ Int64⍰ │ Int64⍰      │ Int64⍰     │ Int64⍰    │
├─────┼────────┼─────────────┼────────────┼───────────┤
│ 1   │ 20     │ 166227      │ 165948     │ 43583     │
│ 2   │ 20     │ 165669      │ 165109     │ 23747     │
│ 3   │ 20     │ 165110      │ 164830     │ 23468     │
│ 4   │ 20     │ 165109      │ 165389     │ 23468     │
│ 5   │ 20     │ 174887      │ 165109     │ 23747     │
│ 6   │ 20     │ 165389      │ 164830     │ 23468     │
│ 7   │ 20     │ 165669      │ 172932     │ 23468     │
│ 8   │ 20     │ 165110      │ 164830     │ 23468     │
│ 9   │ 20     │ 165109      │ 165110     │ 23468     │
│ 10  │ 20     │ 174888      │ 165110     │ 23467     │
⋮
│ 180 │ 360    │ 1229377478  │ 1211158727 │ 251189838 │
│ 181 │ 380    │ 1770644758  │ 1832076364 │ 329687503 │
│ 182 │ 380    │ 1694346878  │ 1844286363 │ 335709665 │
│ 183 │ 380    │ 1697307394  │ 1843063265 │ 334712307 │
│ 184 │ 380    │ 1696633545  │ 1842312868 │ 345839454 │
│ 185 │ 380    │ 1593146248  │ 1745200585 │ 330712521 │
│ 186 │ 380    │ 1595757548  │ 1756007010 │ 338469594 │
│ 187 │ 380    │ 1590972727  │ 1757614803 │ 338160608 │
│ 188 │ 380    │ 1601921075  │ 1777412570 │ 375630112 │
│ 189 │ 380    │ 1752906530  │ 1906711975 │ 369538384 │
│ 190 │ 380    │ 1750165600  │ 1922575330 │ 375538477 │

In [67]:
using Statistics, DataFrames
times_grouped=by(mydata, :size, :time_naive => mean, :time_better => mean)

19×3 DataFrame
│ Row │ size   │ time_naive_mean │ time_better_mean │
│     │ Int64⍰ │ Float64         │ Float64          │
├─────┼────────┼─────────────────┼──────────────────┤
│ 1   │ 20     │ 1.6592e5        │ 1.67317e5        │
│ 2   │ 40     │ 1.29322e6       │ 1.29436e6        │
│ 3   │ 60     │ 4.33302e6       │ 4.34037e6        │
│ 4   │ 80     │ 1.02775e7       │ 1.02899e7        │
│ 5   │ 100    │ 2.07589e7       │ 2.03198e7        │
│ 6   │ 120    │ 3.51866e7       │ 3.49123e7        │
│ 7   │ 140    │ 5.67137e7       │ 5.64147e7        │
│ 8   │ 160    │ 8.60298e7       │ 8.43163e7        │
│ 9   │ 180    │ 1.23647e8       │ 1.20772e8        │
│ 10  │ 200    │ 1.63376e8       │ 1.65707e8        │
│ 11  │ 220    │ 2.17022e8       │ 2.19944e8        │
│ 12  │ 240    │ 2.82775e8       │ 2.86742e8        │
│ 13  │ 260    │ 3.8504e8        │ 3.6753e8         │
│ 14  │ 280    │ 4.49461e8       │ 4.58406e8        │
│ 15  │ 300    │ 5.557e8         │ 6.03674e8        │
│ 16  │ 320    │ 8.67264e8       │ 7.71431e8        │
│ 17  │ 340    │ 1.01919e9       │ 9.71075e8        │
│ 18  │ 360    │ 1.21116e9       │ 1.22913e9        │
│ 19  │ 380    │ 1.82273e9       │ 1.67438e9        │

In [69]:
import Pkg
Pkg.add("Polynomials")

 Resolving package versions...
  Updating `~/.julia/Project.toml`
 [no changes]
  Updating `~/.julia/Manifest.toml`
 [no changes]


In [95]:
x=times_grouped[:size];
y=times_grouped[:time_naive_mean];

In [109]:
using Polynomials
fit=polyfit(x,y,3)

Poly(-1.1041503338856687e8 + 3.809451595750555e6*x - 30234.717818207417*x^2 + 85.89329532901526*x^3)

In [110]:
A=zeros(19,4)
A[:,1]=x.^3
A[:,2]=x.^2
A[:,3]=x
A[:,4]=ones(19)

19-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [111]:
A\y

4-element Array{Float64,1}:
     85.89329532901526    
 -30234.717818207417      
      3.809451595750555e6 
     -1.1041503338856687e8

In [14]:
using(LinearAlgebra)
A=rand(4,3)
QR=qr(A)
Q=QR.Q
R=QR.R
A_new=inv(R)*Q'

3×4 Array{Float64,2}:
  2.38854    0.588179  -1.4215    0.0239848
 -2.97975   -1.81547    3.27974   0.241985 
  0.182803   2.02032   -0.915946  0.0693491

In [15]:
A

4×3 Array{Float64,2}:
 0.919285  0.413326  0.09406 
 0.351423  0.329939  0.678911
 0.994628  0.836992  0.443115
 0.475732  0.353276  0.245949

In [16]:
A_new

3×4 Array{Float64,2}:
  2.38854    0.588179  -1.4215    0.0239848
 -2.97975   -1.81547    3.27974   0.241985 
  0.182803   2.02032   -0.915946  0.0693491

In [17]:
A*A_new*A

4×3 Array{Float64,2}:
 0.919285  0.413326  0.09406 
 0.351423  0.329939  0.678911
 0.994628  0.836992  0.443115
 0.475732  0.353276  0.245949

In [18]:
A_new*A

3×3 Array{Float64,2}:
 1.0          -9.44933e-17  -1.27712e-16
 1.21157e-15   1.0           3.7517e-16 
 9.5039e-17    1.20222e-17   1.0        

In [19]:
A_new*A*A_new

3×4 Array{Float64,2}:
  2.38854    0.588179  -1.4215    0.0239848
 -2.97975   -1.81547    3.27974   0.241985 
  0.182803   2.02032   -0.915946  0.0693491